version: 2.1

jobs:
  hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "hello"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - hello